[package]
name = "tada-adapters"
description = "Object storage, mail and model provider adapters."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tada-app.workspace = true
async-trait.workspace = true
aws-sdk-s3.workspace = true
secrecy.workspace = true
